services:
  - type: web
    name: frontend-workout-bud
    env: static
    buildCommand: cd ui; yarn install --production=false; yarn build
    staticPublishPath: ui/build/
    buildFilter:
      paths:
        - ui/**/*.js
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
  - type: web
    name: backend-workout-bud
    plan: free
    env: node
    buildCommand: cd api; yarn
    startCommand: cd api; yarn start
    buildFilter:
      paths:
        - api/**/*.js
databases:
  - name: database-workout-bud
    plan: free
    databaseName: workoutbud_db
    ipAllowList: [] # only allow internal connections